; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:arduino_nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
lib_deps = 
	esp32async/ESPAsyncWebServer@^3.11.0
	adafruit/Adafruit BMP085 Library@^1.2.4
	bblanchon/ArduinoJson@^7.2.2
board_build.filesystem = littlefs
board_build.partitions = app3M_spiffs9M_fact512k_16MB.csv

;This needs to be uncommented when building or uploading filesystem image
;upload_protocol = esptool